# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"E\n\x07NLImage\x12\r\n\x05\x63olor\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xb0\x01\n\x14NLImageRotateRequest\x12\x30\n\x08rotation\x18\x01 \x01(\x0e\x32\x1e.NLImageRotateRequest.Rotation\x12\x17\n\x05image\x18\x02 \x01(\x0b\x32\x08.NLImage\"M\n\x08Rotation\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nNINETY_DEG\x10\x01\x12\x12\n\x0eONE_EIGHTY_DEG\x10\x02\x12\x13\n\x0fTWO_SEVENTY_DEG\x10\x03\x32\x62\n\x0eNLImageService\x12.\n\x0bRotateImage\x12\x15.NLImageRotateRequest\x1a\x08.NLImage\x12 \n\nMeanFilter\x12\x08.NLImage\x1a\x08.NLImageB\x02P\x01\x62\x06proto3')



_NLIMAGE = DESCRIPTOR.message_types_by_name['NLImage']
_NLIMAGEROTATEREQUEST = DESCRIPTOR.message_types_by_name['NLImageRotateRequest']
_NLIMAGEROTATEREQUEST_ROTATION = _NLIMAGEROTATEREQUEST.enum_types_by_name['Rotation']
NLImage = _reflection.GeneratedProtocolMessageType('NLImage', (_message.Message,), {
  'DESCRIPTOR' : _NLIMAGE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:NLImage)
  })
_sym_db.RegisterMessage(NLImage)

NLImageRotateRequest = _reflection.GeneratedProtocolMessageType('NLImageRotateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NLIMAGEROTATEREQUEST,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:NLImageRotateRequest)
  })
_sym_db.RegisterMessage(NLImageRotateRequest)

_NLIMAGESERVICE = DESCRIPTOR.services_by_name['NLImageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _NLIMAGE._serialized_start=15
  _NLIMAGE._serialized_end=84
  _NLIMAGEROTATEREQUEST._serialized_start=87
  _NLIMAGEROTATEREQUEST._serialized_end=263
  _NLIMAGEROTATEREQUEST_ROTATION._serialized_start=186
  _NLIMAGEROTATEREQUEST_ROTATION._serialized_end=263
  _NLIMAGESERVICE._serialized_start=265
  _NLIMAGESERVICE._serialized_end=363
# @@protoc_insertion_point(module_scope)
